# Generated by Django 4.2.23 on 2026-06-29 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('to_read', 'To Read'), ('reading', 'Currently Reading'), ('completed', 'Completed')], default='to_read', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'work_key')},
            },
        ),
    ]
